services:
  homebox:
    image: homebox
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - COMMIT=head
        - BUILD_TIME=0001-01-01T00:00:00Z
    container_name: homebox
    restart: unless-stopped
    ports:
      - "3100:7745"
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - ./data:/data
